include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/Project.dart"
    - "**/Todo.dart"
  errors:
    invalid_annotation_target: ignore
    argument_type_not_assignable: warning
    invalid_assignment: warning
    implicit_dynamic_type: warning
    implicit_dynamic_list_literal: warning
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    cascade_invocations: false
    unnecessary_this: false
