name: refocus_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  amplify_api: ^0.2.4
  amplify_auth_cognito: ^0.2.4
  amplify_datastore: ^0.2.4
  amplify_flutter: ^0.2.4
  auto_route: ^2.4.0
  awesome_flutter_extensions: ^0.0.1+2
  bloc: ^7.1.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  dartx: ^0.7.1
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^1.9.5
  flutter_slidable: ^0.6.0
  flutter_time_picker_spinner: ^2.0.0
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  google_sign_in: ^5.1.0
  googleapis: ^5.0.0
  googleapis_auth: ^1.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  injectable: ^1.5.0
  internet_connection_checker: ^0.0.1+2
  intl: ^0.17.0
  logger: ^1.1.0
  path_provider: ^2.0.3
  rxdart: ^0.27.2
  shared_preferences: ^2.0.7
  sliding_sheet: ^0.5.0
  styled_widget: ^0.4.0+3
  syncfusion_flutter_calendar: ^19.2.60
  syncfusion_flutter_datepicker: ^19.2.62
  url_launcher: ^6.0.10
  uuid: ^3.0.4

dev_dependencies:
  auto_route_generator: ^2.4.0
  bloc_test: ^8.1.0
  build_runner: ^2.1.2
  flutter_gen_runner: null
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  hive_generator: ^1.1.1
  injectable_generator: ^1.5.2
  json_serializable: ^5.0.2
  mocktail: ^0.1.4
  very_good_analysis: ^2.3.0

flutter_gen: null

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBoldItalic.otf
          style: italic
          weight: 900
        - asset: assets/fonts/Inter-Black.otf
          weight: 800
        - asset: assets/fonts/Inter-BlackItalic.otf
          style: italic
          weight: 800
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-SemiBoldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Italic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/Inter-Light.otf
          weight: 200
        - asset: assets/fonts/Inter-LightItalic.otf
          style: italic
          weight: 200
        - asset: assets/fonts/Inter-Thin.otf
          weight: 100
        - asset: assets/fonts/Inter-ThinItalic.otf
          style: italic
          weight: 100
