name: refocus_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  uuid: ^3.0.4
  # Class helpers
  equatable: ^2.0.3
  # freezed_annotation: ^0.14.3
  # Service locator
  get_it: ^7.2.0
  injectable: ^1.4.1
  # Functional programming stuffs
  dartz: ^0.10.0-nullsafety.2
  # Remote API
  connectivity: ^3.0.6
  internet_connection_checker: ^0.0.1+2
  http: ^0.13.3
  # local cache
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  # Google Calendar
  google_sign_in: ^5.0.5
  extension_google_sign_in_as_googleapis_auth: ^2.0.2
  googleapis: ^4.0.0
  googleapis_auth: ^1.1.0
  url_launcher: ^6.0.9
  # Calendar
  syncfusion_flutter_calendar: ^19.2.49
  # UI Helpers
  styled_widget: ^0.3.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0
  injectable_generator: ^1.4.1
  build_runner: ^2.0.6
  # freezed: ^0.14.3
  # json_serializable: ^5.0.0
  hive_generator: ^1.1.0
  # hive_test: ^1.0.1
flutter:
  uses-material-design: true
  generate: true
