name: refocus_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  uuid: ^3.0.4
  get: ^4.3.4
  # Class helpers
  equatable: ^2.0.3
  # freezed_annotation: ^0.14.3
  # Service locator
  get_it: ^7.2.0
  injectable: ^1.4.1
  # Functional programming stuffs
  dartz: ^0.10.0-nullsafety.2
  # Remote API
  connectivity: ^3.0.6
  internet_connection_checker: ^0.0.1+2
  http: ^0.13.3
  # local cache
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  # Google Calendar
  google_sign_in: ^5.0.5
  extension_google_sign_in_as_googleapis_auth: ^2.0.2
  googleapis: ^4.0.0
  googleapis_auth: ^1.1.0
  url_launcher: ^6.0.9
  # Calendar
  syncfusion_flutter_calendar: ^19.2.49
  date_picker_timeline: ^1.2.3
  # UI Helpers
  styled_widget: ^0.3.1+2
  # Extension
  dartx: ^0.7.1
  # Dev helpers
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0
  injectable_generator: ^1.4.1
  build_runner: ^2.0.6
  # freezed: ^0.14.3
  # json_serializable: ^5.0.0
  hive_generator: ^1.1.0
  flutter_gen_runner:

flutter_gen:

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBoldItalic.otf
          style: italic
          weight: 900
        - asset: assets/fonts/Inter-Black.otf
          weight: 800
        - asset: assets/fonts/Inter-BlackItalic.otf
          style: italic
          weight: 800
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-SemiBoldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Italic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/Inter-Light.otf
          weight: 200
        - asset: assets/fonts/Inter-LightItalic.otf
          style: italic
          weight: 200
        - asset: assets/fonts/Inter-Thin.otf
          weight: 100
        - asset: assets/fonts/Inter-ThinItalic.otf
          style: italic
          weight: 100
