name: refocus_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  equatable: ^2.0.3
  # Service locator
  get_it: ^7.2.0
  # Functional programming stuffs
  dartz: ^0.10.0-nullsafety.2
  # Remote API
  connectivity: ^3.0.6
  http: ^0.13.3
  # local cache
  shared_preferences: ^2.0.6
  # Google Calendar
  googleapis: ^4.0.0
  googleapis_auth: ^1.1.0
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  #mockito: ^5.0.11
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
