name: refocus_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # AWS
  amplify_api: ^0.2.10
  amplify_auth_cognito: ^0.2.6
  amplify_datastore: ^0.2.6
  amplify_flutter: ^0.2.10

  # Routing
  go_router: ^3.0.1

  # Logic
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  formz: ^0.4.1
  dartz: ^0.10.1
  equatable: ^2.0.3

  # Network
  connectivity: ^3.0.6
  internet_connection_checker: ^0.0.1+2
  http: ^0.13.3

  # Google APIs
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  google_sign_in: ^5.2.1
  googleapis: ^7.0.0
  googleapis_auth: ^1.3.0

  # Local Data Store
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.7

  # Misc
  logger: ^1.1.0
  flutter_dotenv: ^5.0.2
  rxdart: ^0.27.2
  url_launcher: ^6.0.10
  freezed_annotation: ^1.1.0
  uuid: ^3.0.5
  dartx: ^1.0.0
  awesome_flutter_extensions: ^0.0.1+2

  get_it: ^7.2.0
  injectable: ^1.5.0
  path_provider: ^2.0.8

  # UI
  cupertino_icons: ^1.0.4
  fluttertoast: ^8.0.8
  flutter_platform_widgets: ^1.9.5
  flutter_slidable: ^1.1.0
  modal_bottom_sheet: ^2.0.0
  styled_widget: ^0.4.0+3
  syncfusion_flutter_calendar: ^19.3.44
  syncfusion_flutter_datepicker: ^19.3.44
  shrink_sidemenu: ^2.0.0+2-null-safety

dev_dependencies:
  auto_route_generator:
  bloc_test: ^9.0.1
  build_runner: ^2.1.0
  #  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  hive_generator: ^1.1.1
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.3
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

#flutter_gen: null

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBoldItalic.otf
          style: italic
          weight: 900
        - asset: assets/fonts/Inter-Black.otf
          weight: 800
        - asset: assets/fonts/Inter-BlackItalic.otf
          style: italic
          weight: 800
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-SemiBoldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Italic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/Inter-Light.otf
          weight: 200
        - asset: assets/fonts/Inter-LightItalic.otf
          style: italic
          weight: 200
        - asset: assets/fonts/Inter-Thin.otf
          weight: 100
        - asset: assets/fonts/Inter-ThinItalic.otf
          style: italic
          weight: 100
